name: Documentation
on:
  push:
    branches: [master]
jobs:
  reference:
    name: Reference
    runs-on: ubuntu-latest
    steps:
      - uses: bobheadxi/deployments@master
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: api
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node_version: 13.x
      - run: yarn install --check-files
      - run: make docs/api
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_key }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret }}
          SOURCE_DIR: docs/api
      - uses: bobheadxi/deployments@master
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://api.denosaur.org
